title: "CTFs For Dummies"
description: "Walkthroughs, cryptography, and CTF-related thing made as simple as possible!"
theme: jekyll-theme-hacker

url: "https://vodomerka-rgb.github.io"
baseurl: "/ctfs-for-dummies"

markdown: kramdown
kramdown:
  math_engine: mathjax

plugins:
  - jekyll-feed

permalink: /:year/:month/:day/:title/

show_excerpts: true
